import Foundation

// MARK: - Errors

enum GenerateSecretsError: Error, CustomStringConvertible {
    case invalidArguments
    case fileNotFound(String)
    case invalidJSON(String)

    var description: String {
        switch self {
        case .invalidArguments:
            return "Usage: GenerateSecrets <input-json-path> <output-swift-path>"
        case .fileNotFound(let path):
            return "error: \(path) not found.\nhint: Run 'direnv allow' in the project directory to generate ios-secrets.json"
        case .invalidJSON(let path):
            return "error: Failed to parse \(path) as JSON dictionary."
        }
    }
}

// MARK: - Functions

/// コマンドライン引数を検証する
func validateArguments(_ arguments: [String]) throws -> (inputPath: String, outputPath: String) {
    guard arguments.count >= 3 else {
        throw GenerateSecretsError.invalidArguments
    }
    return (arguments[1], arguments[2])
}

/// JSONファイルからシークレットを読み込む
func loadSecrets(from path: String) throws -> [String: String] {
    guard FileManager.default.fileExists(atPath: path) else {
        throw GenerateSecretsError.fileNotFound(path)
    }

    let inputURL = URL(fileURLWithPath: path)
    let jsonData = try Data(contentsOf: inputURL)

    guard let secrets = try JSONSerialization.jsonObject(with: jsonData) as? [String: String] else {
        throw GenerateSecretsError.invalidJSON(path)
    }

    return secrets
}

/// Swiftコードをファイルに書き込む
func writeSwiftCode(_ code: String, to path: String) throws {
    let outputURL = URL(fileURLWithPath: path)
    try code.write(to: outputURL, atomically: true, encoding: .utf8)
}

/// SNAKE_CASE を camelCase に変換する
/// 例: SUPABASE_PROJECT_URL → supabaseProjectUrl
func snakeToCamelCase(_ input: String) -> String {
    let lowercased = input.lowercased()
    var result = ""
    var capitalizeNext = false

    for char in lowercased {
        if char == "_" {
            capitalizeNext = true
        } else if capitalizeNext {
            result.append(char.uppercased())
            capitalizeNext = false
        } else {
            result.append(char)
        }
    }

    return result
}

/// シークレットからSwiftコードを生成する
func generateSwiftCode(from secrets: [String: String]) -> String {
    let sortedKeys = secrets.keys.sorted()

    var privateVars: [String] = []
    var publicVars: [String] = []

    for key in sortedKeys {
        let value = secrets[key] ?? ""
        let swiftName = snakeToCamelCase(key)

        privateVars.append("    private static let _\(swiftName) = \"\(value)\"")
        publicVars.append("""
            public static var \(swiftName): String {
                guard !_\(swiftName).isEmpty else {
                    fatalError("Secrets.\(swiftName) is not configured. Check ios-secrets.json")
                }
                return _\(swiftName)
            }
        """)
    }

    return """
    // Auto-generated by GenerateSecrets - DO NOT EDIT
    import Foundation

    public enum Secrets {
    \(privateVars.joined(separator: "\n"))

    \(publicVars.joined(separator: "\n\n"))
    }
    """
}

// MARK: - Main

func main() throws {
    let (inputPath, outputPath) = try validateArguments(CommandLine.arguments)
    let secrets = try loadSecrets(from: inputPath)
    let swiftCode = generateSwiftCode(from: secrets)
    try writeSwiftCode(swiftCode, to: outputPath)
    print("Generated \(outputPath)")
}

do {
    try main()
} catch {
    fputs("\(error)\n", stderr)
    exit(1)
}
